In [1]:
import pandas as pd
import numpy as np

In [2]:
billing = pd.read_csv('Raw nexa data/billing.csv')
cities = pd.read_csv('Raw nexa data/cities.csv')
customers = pd.read_csv('Raw nexa data/customers.csv')
devices = pd.read_csv('Raw nexa data/devices.csv')
payments = pd.read_csv('Raw nexa data/payments.csv')
plans = pd.read_csv('Raw nexa data/plans.csv')
subscriptions = pd.read_csv('Raw nexa data/subscriptions.csv')
customer_feedback = pd.read_csv('Raw nexa data/customer_feedback.csv')
contracts = pd.read_csv('Raw nexa data/contracts.csv')
complaints = pd.read_csv('Raw nexa data/complaints.csv')
data_quality_issue_log= pd.read_csv('Raw nexa data/data_quality_issue_log.csv')
employees = pd.read_csv('Raw nexa data/employees.csv')
marketing_campaigns = pd.read_csv('Raw nexa data/marketing_campaigns.csv')
network_quality = pd.read_csv('Raw nexa data/network_quality.csv')
plan_history = pd.read_csv('Raw nexa data/plan_history.csv')
recharges= pd.read_csv('Raw nexa data/recharges.csv')
regions = pd.read_csv('Raw nexa data/regions.csv')
retention_campaigns = pd.read_csv('Raw nexa data/retention_campaigns.csv')
states = pd.read_csv('Raw nexa data/states.csv')
stores = pd.read_csv('Raw nexa data/stores.csv')
support_tickets = pd.read_csv('Raw nexa data/support_tickets.csv')
usage_data = pd.read_csv('Raw nexa data/usage_data.csv')
usage_sms = pd.read_csv('Raw nexa data/usage_sms.csv')
usage_voice = pd.read_csv('Raw nexa data/usage_voice.csv')

In [16]:
complaints

,complaint_id,customer_id,complaint_date,complaint_type,severity,status,resolution_date
0,CMP00000001,C0000001,30-06-2020,Data Speed,Major,Unresolved,NaN
1,CMP00000002,C0000002,01-12-2015,Network Coverage,Moderate,Resolved,02-12-2015
2,CMP00000003,C0000003,09-10-2014,Wrongful Charge,Major,Unresolved,NaN
3,CMP00000004,C0000005,05-09-2016,Network Coverage,Severe,Unresolved,NaN
4,CMP00000005,C0000005,18-04-2014,Recharge Not Credited,Major,Unresolved,NaN
...,...,...,...,...,...,...,...
16579,CMP00016580,C0018997,04-07-2014,Service Quality,Moderate,Unresolved,NaN
16580,CMP00016581,C0018998,28-04-2023,Recharge Not Credited,Minor,Unresolved,NaN
16581,CMP00016582,C0018998,21-10-2014,Customer Service,Moderate,Resolved,29-10-2014
16582,CMP00016583,C0018999,30-01-2015,Data Speed,Minor,Unresolved,NaN
16583,CMP00016584,C0019000,03-03-2018,Connection Down,Moderate,Unresolved,NaN

In [6]:
plans["product_line"].value_counts()

product_line
Prepaid Mobile     6
Postpaid Mobile    5
Fiber Broadband    4
5G                 3
OTT Bundles        2
Enterprise         2
IoT Solutions      2
Smart Home         1
Name: count, dtype: int64

START CLEANING

In [393]:
billing.isnull().sum()

invoice_id              0
customer_id             0
billing_date            0
billing_period_month    0
base_amount_inr         0
gst_amount_inr          0
total_amount_inr        0
due_date                0
payment_status          0
dtype: int64

In [394]:
# Remove Duplicates
billing.drop_duplicates(inplace=True)
billing.duplicated().sum()

np.int64(0)

In [395]:
billing.dtypes

invoice_id                  str
customer_id                 str
billing_date                str
billing_period_month        str
base_amount_inr         float64
gst_amount_inr          float64
total_amount_inr        float64
due_date                    str
payment_status              str
dtype: object

In [396]:
billing['billing_date'] = pd.to_datetime(billing['billing_date'], format='%d-%m-%Y', errors='coerce')
billing['due_date'] = pd.to_datetime(billing['due_date'], format='%d-%m-%Y', errors='coerce')

billing['billing_period_month'] = pd.to_datetime(billing['billing_period_month'], format='%m-%Y', errors='coerce')

In [397]:
# GST expected calculation with 2 decimals
billing['gst_expected'] = (billing['base_amount_inr'] * 0.18).round(2)

# Mismatch flag (compare with 2-decimal rounded values)
billing['gst_mismatch'] = ~np.isclose(
    billing['gst_amount_inr'].round(2),
    billing['gst_expected'],
    atol=0.01
)

In [398]:
billing.loc[billing['total_amount_inr'] < 0, 'total_amount_inr'] = np.nan

In [399]:
cities.isnull().sum()

city_id       0
city_name     0
state_id      0
state_name    0
zone          0
region_id     0
tier          0
pin_prefix    0
dtype: int64

In [400]:
cities.duplicated().sum()

np.int64(0)

In [401]:
cities.dtypes

city_id         str
city_name       str
state_id        str
state_name      str
zone            str
region_id       str
tier            str
pin_prefix    int64
dtype: object

In [402]:
complaints.isnull().sum()

complaint_id          0
customer_id           0
complaint_date        0
complaint_type        0
severity              0
status                0
resolution_date    7348
dtype: int64

In [403]:
complaints.duplicated().sum()

np.int64(0)

In [404]:
complaints.dtypes

complaint_id       str
customer_id        str
complaint_date     str
complaint_type     str
severity           str
status             str
resolution_date    str
dtype: object

In [405]:
#date conversion
complaints['complaint_date'] = pd.to_datetime(complaints['complaint_date'], format='%d-%m-%Y', errors='coerce')
complaints['resolution_date'] = pd.to_datetime(complaints['resolution_date'], format='%d-%m-%Y', errors='coerce')

In [406]:
contracts.isnull().sum()

contract_id               0
customer_id               0
plan_id                   0
contract_type             0
contract_length_months    0
start_date                0
end_date                  0
auto_renew                0
renewal_status            0
dtype: int64

In [407]:
contracts.duplicated().sum()

np.int64(0)

In [408]:
contracts.dtypes

contract_id                 str
customer_id                 str
plan_id                     str
contract_type               str
contract_length_months    int64
start_date                  str
end_date                    str
auto_renew                  str
renewal_status              str
dtype: object

In [409]:
contracts['start_date'] = pd.to_datetime(contracts['start_date'], format='%d-%m-%Y', errors='coerce')
contracts['end_date'] = pd.to_datetime(contracts['end_date'], format='%d-%m-%Y', errors='coerce')

In [410]:
customer_feedback.isnull().sum()

feedback_id          0
customer_id          0
feedback_date        0
csat_score           0
nps_score            0
channel              0
feedback_category    0
dtype: int64

In [411]:
customer_feedback.duplicated().sum()

np.int64(0)

In [412]:
customer_feedback.dtypes

feedback_id            str
customer_id            str
feedback_date          str
csat_score           int64
nps_score            int64
channel                str
feedback_category      str
dtype: object

In [413]:
customer_feedback['feedback_date'] = pd.to_datetime(customer_feedback['feedback_date'], format='%d-%m-%Y', errors='coerce')

In [414]:
customers.isnull().sum()

customer_id                0
first_name                 0
last_name                  0
gender                     0
date_of_birth              0
age                        0
email                    745
phone_number               0
address                  380
city_id                    0
city_name                  0
state_id                   0
pin_code                   0
city_tier                  0
region_id                  0
occupation                 0
annual_income_inr        954
customer_segment           0
product_line               0
plan_id                    0
acquisition_channel        0
acquisition_date           0
tenure_months              0
customer_status            0
churn_date             15560
dtype: int64

In [415]:
#remove dupicates
customers.drop_duplicates(inplace=True)
customers.duplicated().sum()

np.int64(0)

In [416]:
customers.dtypes

customer_id                str
first_name                 str
last_name                  str
gender                     str
date_of_birth              str
age                      int64
email                      str
phone_number             int64
address                    str
city_id                    str
city_name                  str
state_id                   str
pin_code                 int64
city_tier                  str
region_id                  str
occupation                 str
annual_income_inr      float64
customer_segment           str
product_line               str
plan_id                    str
acquisition_channel        str
acquisition_date           str
tenure_months            int64
customer_status            str
churn_date                 str
dtype: object

In [417]:
customers['date_of_birth'] = pd.to_datetime(customers['date_of_birth'], format='%d-%m-%Y', errors='coerce')
today = pd.Timestamp.today()
customers['age_recalc'] = (today.year - customers['date_of_birth'].dt.year) - (
    (today.month < customers['date_of_birth'].dt.month) | 
    ((today.month == customers['date_of_birth'].dt.month) & (today.day < customers['date_of_birth'].dt.day))
)

In [418]:
#date conversion
customers['date_of_birth'] = pd.to_datetime(customers['date_of_birth'], format='%d-%m-%Y', errors='coerce')
customers["acquisition_date"] = pd.to_datetime(customers["acquisition_date"], format='%d-%m-%Y', errors='coerce')
customers["churn_date"] = pd.to_datetime(customers["churn_date"], format='%d-%m-%Y', errors='coerce')

In [419]:
data_quality_issue_log.isnull().sum()

table            0
issue_type       0
rows_affected    0
dtype: int64

In [420]:
data_quality_issue_log.duplicated().sum()

np.int64(0)

In [421]:
data_quality_issue_log.dtypes

table              str
issue_type         str
rows_affected    int64
dtype: object

In [422]:
devices.isnull().sum()

device_id           0
customer_id         0
brand               0
model               0
device_type         0
device_price_inr    0
purchase_date       0
imei                0
dtype: int64

In [423]:
devices.duplicated().sum()

np.int64(0)

In [424]:
devices.dtypes

device_id             str
customer_id           str
brand                 str
model                 str
device_type           str
device_price_inr    int64
purchase_date         str
imei                int64
dtype: object

In [425]:
devices['purchase_date'] = pd.to_datetime(devices['purchase_date'], format='%d-%m-%Y', errors='coerce')

In [426]:
employees.isnull().sum()

employee_id      0
employee_name    0
gender           0
department       0
role             0
store_id         0
region_id        0
hire_date        0
email            0
dtype: int64

In [427]:
employees.duplicated().sum()

np.int64(0)

In [428]:
employees.dtypes

employee_id      str
employee_name    str
gender           str
department       str
role             str
store_id         str
region_id        str
hire_date        str
email            str
dtype: object

In [429]:
employees["hire_date"] = pd.to_datetime(employees["hire_date"], format='%d-%m-%Y', errors='coerce')

In [430]:
marketing_campaigns.isnull().sum()

campaign_id          0
campaign_name        0
channel              0
target_segment       0
start_date           0
end_date             0
budget_inr           0
customers_reached    0
conversions          0
dtype: int64

In [431]:
marketing_campaigns.duplicated().sum()

np.int64(0)

In [432]:
marketing_campaigns.dtypes

campaign_id            str
campaign_name          str
channel                str
target_segment         str
start_date             str
end_date               str
budget_inr           int64
customers_reached    int64
conversions          int64
dtype: object

In [433]:
marketing_campaigns["start_date"] = pd.to_datetime(marketing_campaigns["start_date"], format='%d-%m-%Y', errors='coerce')
marketing_campaigns["end_date"] = pd.to_datetime(marketing_campaigns["end_date"], format='%d-%m-%Y', errors='coerce')

In [434]:
network_quality.isnull().sum()

record_id                  0
customer_id                0
city_id                    0
month                      0
avg_signal_strength_dbm    0
dropped_call_rate_pct      0
avg_download_speed_mbps    0
network_downtime_hours     0
dtype: int64

In [435]:
network_quality.duplicated().sum()

np.int64(0)

In [436]:
payments.isnull().sum()

payment_id        0
invoice_id        0
customer_id       0
payment_date      0
amount_inr        0
payment_method    0
payment_status    0
dtype: int64

In [437]:
payments.duplicated().sum()

np.int64(276)

In [438]:
valid_invoices = billing['invoice_id'].unique()
payments = payments[payments['invoice_id'].isin(valid_invoices)]

In [439]:
payments = payments.drop_duplicates(subset=['payment_id'])

In [440]:
plan_history.isnull().sum()

history_id       0
customer_id      0
old_plan_id      0
new_plan_id      0
change_date      0
change_reason    0
dtype: int64

In [441]:
plan_history['new_plan_id'].unique()

<StringArray>
['PL010', 'PL004', 'PL021', 'PL001', 'PL018', 'PL014', 'PL024', 'PL020',
 'PL016', 'PL023', 'PL002', 'PL009', 'PL003', 'PL005', 'PL012', 'PL013',
 'PL008', 'PL006', 'PL015', 'PL019', 'PL022', 'PL017', 'PL007', 'PL011',
 'PL025']
Length: 25, dtype: str

In [442]:
plan_history.duplicated().sum()

np.int64(0)

In [443]:
plan_history.dtypes

history_id       str
customer_id      str
old_plan_id      str
new_plan_id      str
change_date      str
change_reason    str
dtype: object

In [444]:
plan_history["change_date"] = pd.to_datetime(plan_history["change_date"], format='%d-%m-%Y', errors='coerce')

In [445]:
plans.isnull().sum()

plan_id           0
plan_name         0
product_line      0
billing_cycle     0
monthly_charge    0
data_quota_gb     0
voice_minutes     0
sms_count         0
segment           0
is_active         0
dtype: int64

In [446]:
plans.duplicated().sum()

np.int64(0)

In [447]:
plans.dtypes

plan_id             str
plan_name           str
product_line        str
billing_cycle       str
monthly_charge    int64
data_quota_gb     int64
voice_minutes     int64
sms_count         int64
segment             str
is_active           str
dtype: object

In [448]:
recharges.isnull().sum()

recharge_id       0
customer_id       0
recharge_date     0
amount_inr        0
plan_id           0
payment_method    0
dtype: int64

In [449]:
recharges.duplicated().sum()

np.int64(0)

In [450]:
recharges.dtypes

recharge_id           str
customer_id           str
recharge_date         str
amount_inr        float64
plan_id               str
payment_method        str
dtype: object

In [451]:
recharges["recharge_date"] = pd.to_datetime(recharges["recharge_date"], format='%d-%m-%Y', errors='coerce')

In [452]:
regions.isnull().sum()

region_id       0
region_name     0
zone_hq_city    0
dtype: int64

In [453]:
regions.duplicated().sum()

np.int64(0)

In [454]:
retention_campaigns.isnull().sum()

campaign_id      0
customer_id      0
campaign_name    0
offer_type       0
contact_date     0
channel          0
response         0
retained_flag    0
dtype: int64

In [455]:
retention_campaigns.duplicated().sum()

np.int64(0)

In [456]:
retention_campaigns.dtypes

campaign_id      str
customer_id      str
campaign_name    str
offer_type       str
contact_date     str
channel          str
response         str
retained_flag    str
dtype: object

In [457]:
retention_campaigns["contact_date"] = pd.to_datetime(retention_campaigns["contact_date"], format='%d-%m-%Y', errors='coerce')

In [458]:
states.isnull().sum()

state_id      0
state_name    0
state_code    0
zone          0
dtype: int64

In [459]:
states.duplicated().sum()

np.int64(0)

In [460]:
stores.isnull().sum()

store_id       0
store_name     0
city_id        0
state_id       0
region_id      0
store_type     0
opened_date    0
dtype: int64

In [461]:
stores.duplicated().sum()

np.int64(0)

In [462]:
stores.dtypes

store_id       str
store_name     str
city_id        str
state_id       str
region_id      str
store_type     str
opened_date    str
dtype: object

In [463]:
stores["opened_date"] = pd.to_datetime(stores["opened_date"], format='%d-%m-%Y', errors='coerce')

In [464]:
subscriptions.isnull().sum()

subscription_id            0
customer_id                0
plan_id                   41
start_date                 0
end_date               17017
billing_cycle              0
monthly_charge_inr         0
subscription_status        0
dtype: int64

In [465]:
subscriptions.duplicated().sum()

np.int64(0)

In [466]:
import pandas as pd

# Step 1: Ensure change_date is parsed correctly
plan_history['change_date'] = pd.to_datetime(
    plan_history['change_date'], format='%d-%m-%Y', errors='coerce'
)

# Step 2: Get latest new_plan_id per customer
latest_plan = (
    plan_history.sort_values('change_date')
    .groupby('customer_id')
    .tail(1)[['customer_id','new_plan_id']]
)

# Rename column to plan_id for consistency
latest_plan.rename(columns={'new_plan_id':'plan_id'}, inplace=True)

# Step 3: Merge with subscriptions
subscriptions = subscriptions.merge(
    latest_plan, on='customer_id', how='left', suffixes=('', '_hist')
)

# Step 4: Fill missing plan_id from latest_plan
subscriptions['plan_id'] = subscriptions['plan_id'].fillna(subscriptions['plan_id_hist'])
subscriptions.drop(columns=['plan_id_hist'], inplace=True)

# Step 5: Final check
missing_after = subscriptions['plan_id'].isnull().sum()
print("Remaining null plan_id after recovery:", missing_after)

# Optional: Drop rows if still null
subscriptions = subscriptions[subscriptions['plan_id'].notnull()]

Remaining null plan_id after recovery: 18

In [467]:
valid_plans = plans['plan_id'].unique()
subscriptions = subscriptions[subscriptions['plan_id'].isin(valid_plans)]

In [468]:
subscriptions.dtypes

subscription_id            str
customer_id                str
plan_id                    str
start_date                 str
end_date                   str
billing_cycle              str
monthly_charge_inr     float64
subscription_status        str
dtype: object

In [469]:
subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"], format='%d-%m-%Y', errors='coerce')
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"], format='%d-%m-%Y', errors='coerce')

In [470]:
subscriptions[(subscriptions["end_date"].isnull()) &(subscriptions["subscription_status"] == "terminated")].shape

(0, 8)

In [471]:
support_tickets.isnull().sum()

ticket_id                       0
customer_id                     0
created_date                    0
category                        0
priority                        0
channel                         0
status                          0
first_contact_resolution        0
assigned_employee_id            0
resolution_hours            13366
resolution_date             13366
dtype: int64

In [472]:
support_tickets.duplicated().sum()

np.int64(0)

In [473]:
support_tickets.dtypes

ticket_id                       str
customer_id                     str
created_date                    str
category                        str
priority                        str
channel                         str
status                          str
first_contact_resolution        str
assigned_employee_id            str
resolution_hours            float64
resolution_date                 str
dtype: object

In [474]:
support_tickets["created_date"] = pd.to_datetime(support_tickets["created_date"], format='%d-%m-%Y', errors='coerce')
support_tickets["first_contact_resolution"] = pd.to_datetime(support_tickets["first_contact_resolution"], format='%d-%m-%Y', errors='coerce')

In [475]:
usage_data.isnull().sum()

usage_id         0
customer_id      0
usage_month      0
data_gb_used     0
data_sessions    0
dtype: int64

In [482]:
usage_data

,usage_id,customer_id,usage_month,data_gb_used,data_sessions,usage_status
0,UD00000001,C0000001,03-2026,22.35,1047,Normal
1,UD00000002,C0000001,02-2026,13.24,61,Normal
2,UD00000003,C0000001,01-2026,13.09,1039,Normal
3,UD00000004,C0000002,03-2026,167.23,442,Normal
4,UD00000005,C0000002,02-2026,109.72,481,Normal
...,...,...,...,...,...,...
56995,UD00056996,C0018999,02-2026,12.64,352,Normal
56996,UD00056997,C0018999,01-2026,13.70,464,Normal
56997,UD00056998,C0019000,03-2026,31.55,1022,Normal
56998,UD00056999,C0019000,02-2026,27.59,783,Normal
56999,UD00057000,C0019000,01-2026,32.24,651,Normal

In [477]:
usage_data.duplicated().sum()

np.int64(0)

In [481]:
usage_data.dtypes

usage_id             str
customer_id          str
usage_month          str
data_gb_used     float64
data_sessions      int64
usage_status         str
dtype: object

In [480]:
mean = usage_data['data_gb_used'].mean()
std = usage_data['data_gb_used'].std()

# Flagging outliers and labeling them
usage_data['usage_status'] = usage_data['data_gb_used'].apply(
    lambda x: 'Outlier' if (x > mean + 3*std) or (x < 0) else 'Normal'
)

In [483]:
usage_sms.isnull().sum()

usage_id        0
customer_id     0
usage_month     0
sms_sent        0
sms_received    0
dtype: int64

In [485]:
usage_sms.duplicated().sum()

np.int64(0)

In [486]:
usage_sms.dtypes

usage_id          str
customer_id       str
usage_month       str
sms_sent        int64
sms_received    int64
dtype: object

In [488]:
usage_voice.duplicated().sum()

np.int64(0)

In [489]:
usage_voice.dtypes

usage_id                str
customer_id             str
usage_month             str
voice_minutes_used    int64
outgoing_calls        int64
incoming_calls        int64
dtype: object

In [491]:
#save files in Cleaned nexa data
billing.to_csv('Cleaned nexa data/billing.csv', index=False)
cities.to_csv('Cleaned nexa data/cities.csv', index=False)
customers.to_csv('Cleaned nexa data/customers.csv', index=False)
devices.to_csv('Cleaned nexa data/devices.csv', index=False)
employees.to_csv('Cleaned nexa data/employees.csv', index=False)    
payments.to_csv('Cleaned nexa data/payments.csv', index=False)
plans.to_csv('Cleaned nexa data/plans.csv', index=False)
subscriptions.to_csv('Cleaned nexa data/subscriptions.csv', index=False)
support_tickets.to_csv('Cleaned nexa data/support_tickets.csv', index=False)
usage_data.to_csv('Cleaned nexa data/usage_data.csv', index=False)
usage_sms.to_csv('Cleaned nexa data/usage_sms.csv', index=False)    
usage_voice.to_csv('Cleaned nexa data/usage_voice.csv', index=False)
complaints.to_csv('Cleaned nexa data/complaints.csv', index=False)
retention_campaigns.to_csv('Cleaned nexa data/retention_campaigns.csv', index=False)
stores.to_csv('Cleaned nexa data/stores.csv', index=False)
states.to_csv('Cleaned nexa data/states.csv', index=False)
plan_history.to_csv('Cleaned nexa data/plan_history.csv', index=False)
recharges.to_csv('Cleaned nexa data/recharges.csv', index=False)
regions.to_csv('Cleaned nexa data/regions.csv', index=False)
contracts.to_csv('Cleaned nexa data/contracts.csv', index=False)
data_quality_issue_log.to_csv('Cleaned nexa data/data_quality_issue_log.csv', index=False)
network_quality.to_csv('Cleaned nexa data/network_quality.csv', index=False)
marketing_campaigns.to_csv('Cleaned nexa data/marketing_campaigns.csv', index=False)
customer_feedback.to_csv('Cleaned nexa data/customer_feedback.csv', index=False)